# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application for test

on:
  schedule:
    - cron: '00 7 1/2 * *'
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pybase64 simplejson pyaes pyinstaller
        pyinstaller -F exec/ss_get_node.py
    - name: Upload file
      uses: actions/upload-artifact@v3
      with:
        path: |
          dist
